### ISSUE TITLE
When clicking install iPA, it says certificate invalid.

### ISSUE THREAD

**Issue by plutinium** [iineva/ipa-server#14]

**Comment by iineva** [comment]
Please make sure caddy server is setup.

发自我的 iPhone

**Comment by plutinium** [comment]
Caddy is setup, but it is making a HTTP server on port 2015

**Comment by iineva** [comment]
you must use https on port 443.
details on caddy document.

发自我的 iPhone

**Comment by plutinium** [comment]
Now I am getting ¨Cannot connect to mydomain.com¨" (With my own domain obviously)

**Comment by plutinium** [comment]
![image](https://user-images.githubusercontent.com/46986457/54168938-0daaea00-442e-11e9-96c5-069c1bb4be77.png)

**Comment by iineva** [comment]
or you can try this

```yml
version: "2"

services:
  web:
    build: .
    container_name: ipa-server
    restart: always
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://ipa.plutinium.com
    volumes:
      - "/docker/data/ipa-server:/app/upload"
  caddy:
    image: abiosoft/caddy:0.11.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    entrypoint: |
      sh -c 'echo "$$CADDY_CONFIG" > /etc/Caddyfile && /usr/bin/caddy --conf /etc/Caddyfile --log stdout'
    environment:
      CADDY_CONFIG: |
        ipa.plutinium.com {
          gzip
          proxy / web:8080
        }
```
