### ISSUE TITLE
关于反代的一个问题

### ISSUE THREAD

**Issue by MengSama** [iineva/ipa-server#3]
我已经搭建好 IPA-Server 了 使用的是 宝塔 Nginx 反向代理 使用发送的域名 为什么不能上传APP?

必须通过 9008 端口的地址上传才有效，并且会立刻刷新显示，而反代域名有缓存 无法做到实时上传更新列表

**Comment by iineva** [comment]
反向代理有缓存不能实时刷新很正常，如果不能正常上传，请检查一下反向代理配置，我不清楚你是怎么配置的，可以尝试先关闭代理缓存

**Comment by MengSama** [comment]
按照您提供的 完全部署 yml 里面的配置 还有一个问题就是 <domain_name> 是反代域名 还是 解析到 ipa-server 的域名?

**Comment by iineva** [comment]
公网域名，相当于我提供的demo里面的 ipa.ineva.cn

**Comment by MengSama** [comment]
好的。谢谢，您的域名上传后会实时刷新显示。

**Comment by iineva** [comment]
按照你这个情况，不需要A域名，B域名反向代理到ipa server服务器的ip地址上对应端口即可。
还有如果AB域名都指向同一台服务器，嗯话，去掉A域名，B域名指向localhost:9008即可

**Comment by MengSama** [comment]
感谢解答。
下面是反代的相关配置
````
 location / 
    {
        proxy_pass http://ip:9008;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
                
        #持久化连接相关配置
        #proxy_connect_timeout 30s;
        #proxy_read_timeout 86400s;
        #proxy_send_timeout 30s;
        #proxy_http_version 1.1;
        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
        
        add_header X-Cache $upstream_cache_status;
        
        expires 12h;
    }
    
    location ~ .*\.(php|jsp|cgi|asp|aspx|flv|swf|xml)?$
    {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_pass http://ip:9008;
        
    }
    
    location ~ .*\.(html|htm|png|gif|jpeg|jpg|bmp|js|css)?$
    {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_pass http://ip:9008;
        
        #缓存相关配置
        #proxy_cache cache_one;
        #proxy_cache_key $host$request_uri$is_args$args;
        #proxy_cache_valid 200 304 301 302 1h;
        
        expires 24h;
    }
    #PROXY-END
````

下面是 yml的配置。
````
# ***** Replace ALL <YOUR_DOMAIN> to you really domain *****

version: "2"

services:
  web:
    build: .
    container_name: ipa-server
    restart: always
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://xxxx.com
    ports:
      - "9008:8080"
    volumes:
      - "/docker/data/ipa-server:/app/upload"
  caddy:
    image: ineva/caddy:0.10.3
    restart: always
    network_mode: host
    entrypoint: |
      sh -c 'echo "$$CADDY_CONFIG" > /etc/Caddyfile && /usr/bin/caddy --conf /etc/Caddyfile --log stdout'
    environment:
      CADDY_CONFIG: |
        xxxx.com {
          gzip
          proxy / localhost:9008
        }
````
方便帮我看看 配置有什么问题吗?

**Comment by iineva** [comment]
我长期使用caddy做网关，对nginx细节配置不是很熟悉，你得确定你的nginx配置开启了https，这样才能在iPhone上正常安装。

如果使用nginx做网关，不需要caddy，yml这样就行了

```yaml
version: "2"

services:
  web:
    build: .
    container_name: ipa-server
    restart: always
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://xxxx.com
    ports:
      - "9008:8080"
    volumes:
      - "/docker/data/ipa-server:/app/upload"
```
