### ISSUE TITLE
通过域名上传ipa报错

### ISSUE THREAD

**Issue by pxvp2008** [iineva/ipa-server#73]
环境：
使用docker-compose部署，只部署ineva/ipa-server:v2.5.3镜像，将8080端口映射出来

docker-compose.yaml文件如下：

```yaml
version: "3.7"

services:
  web:
    image: ineva/ipa-server:v2.5.3
    container_name: ipa-server
    restart: unless-stopped
    environment:
      # server public url
      - PUBLIC_URL=https://aa.123za.com:9981
      # option, remote storager config, s3://ENDPOINT:AK:SK:BUCKET, alioss://ENDPOINT:AK:SK:BUCKET, qiniu://[ZONE]:AK:SK:BUCKET
      - REMOTE=
      # option, remote storager public url, https://cdn.example.com
      - REMOTE_URL=
      # option, metadata storage path, use random secret path to keep your metadata safer in case of remote storage
      - META_PATH=appList.json
      # delete app enabled, true/false
      - DELETE_ENABLED=true
      # meta data 过滤显示, string list, 使用逗号分隔
      - META_DATA_FILTER="key1,key2"
      # 如果设置了，使用此用户名密码来上传和删除App
      - LOGIN_USER=
      - LOGIN_PASS=
    volumes:
      - "./ipa-server/upload:/app/upload"
    ports:
      - "5432:8080"
```

再使用nginx进行代理，nginx的9981代理到ipa-server的5432，nginx中配置了ssl证书。

通过https://aa.123za.com:9981访问的时候，上传ipa包时报如下错误：

ts="2025-02-09 23:26:08.459" caller=ipasd.go:145 msg="err: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"

直接通过http://IP:5432 访问时，可以正常上传ipa包。

请教大佬，如何解决该问题？
